/**
 * All 257 Bulgarian settlements with official town/city status (гр.).
 * Source: National Statistical Institute (NSI), National Register of Settlements.
 * Retrieved: 2026-10-03. Register metadata: current to 2026-05-15.
 * Names/provinces: https://nrnm.nsi.bg/ekatte/zip/download?files_type=json
 * Filter: ek_atte.json t_v_m === "гр."; province join: ek_obl.json.
 * Latin spellings use NSI name_en, with display capitalization normalized.
 * SOF is labeled "Sofia City"; SFO is labeled "Sofia".
 * Coordinates: https://nrnm.nsi.bg/spatial-data-files
 * Download: https://nrnm.nsi.bg/download/4/spatial-data-files
 * Dataset: SU_BG_NSI_NM_2025_1.gpkg (v2025.1; reference 2025-12-31).
 * Joined by EKATTE ID; both sources contain exactly the same 257 town IDs.
 * WGS 84 / EPSG:4326: lat = ycoord, lon = xcoord, rounded to 2 decimals.
 * Coordinates are approximate settlement points, not boundaries.
 * Source attribution must be retained when reusing NSI data.
 *
 * Note: names are not unique — Byala exists in both Varna and Ruse
 * provinces, so identify a town by name AND region.
 */

import type { CityEntry } from './cities';

export const BULGARIAN_TOWNS: CityEntry[] = [
  // Sofia City (4)
  { name: "Bankya", region: "Sofia City", country: "Bulgaria", lat: 42.71, lon: 23.15 },
  { name: "Buhovo", region: "Sofia City", country: "Bulgaria", lat: 42.76, lon: 23.57 },
  { name: "Novi Iskar", region: "Sofia City", country: "Bulgaria", lat: 42.82, lon: 23.35 },
  { name: "Sofia", region: "Sofia City", country: "Bulgaria", lat: 42.70, lon: 23.32 },
  // Sofia (18)
  { name: "Botevgrad", region: "Sofia", country: "Bulgaria", lat: 42.91, lon: 23.79 },
  { name: "Bozhurishte", region: "Sofia", country: "Bulgaria", lat: 42.76, lon: 23.20 },
  { name: "Dolna Banya", region: "Sofia", country: "Bulgaria", lat: 42.31, lon: 23.76 },
  { name: "Dragoman", region: "Sofia", country: "Bulgaria", lat: 42.92, lon: 22.93 },
  { name: "Elin Pelin", region: "Sofia", country: "Bulgaria", lat: 42.67, lon: 23.60 },
  { name: "Etropole", region: "Sofia", country: "Bulgaria", lat: 42.83, lon: 24.00 },
  { name: "Godech", region: "Sofia", country: "Bulgaria", lat: 43.01, lon: 23.05 },
  { name: "Ihtiman", region: "Sofia", country: "Bulgaria", lat: 42.44, lon: 23.82 },
  { name: "Koprivshtitsa", region: "Sofia", country: "Bulgaria", lat: 42.64, lon: 24.36 },
  { name: "Kostenets", region: "Sofia", country: "Bulgaria", lat: 42.31, lon: 23.86 },
  { name: "Kostinbrod", region: "Sofia", country: "Bulgaria", lat: 42.81, lon: 23.22 },
  { name: "Momin Prohod", region: "Sofia", country: "Bulgaria", lat: 42.33, lon: 23.87 },
  { name: "Pirdop", region: "Sofia", country: "Bulgaria", lat: 42.70, lon: 24.19 },
  { name: "Pravets", region: "Sofia", country: "Bulgaria", lat: 42.89, lon: 23.92 },
  { name: "Samokov", region: "Sofia", country: "Bulgaria", lat: 42.34, lon: 23.56 },
  { name: "Slivnitsa", region: "Sofia", country: "Bulgaria", lat: 42.85, lon: 23.04 },
  { name: "Svoge", region: "Sofia", country: "Bulgaria", lat: 42.96, lon: 23.35 },
  { name: "Zlatitsa", region: "Sofia", country: "Bulgaria", lat: 42.71, lon: 24.14 },
  // Plovdiv (18)
  { name: "Asenovgrad", region: "Plovdiv", country: "Bulgaria", lat: 42.01, lon: 24.88 },
  { name: "Banya", region: "Plovdiv", country: "Bulgaria", lat: 42.55, lon: 24.83 },
  { name: "Brezovo", region: "Plovdiv", country: "Bulgaria", lat: 42.35, lon: 25.08 },
  { name: "Hisarya", region: "Plovdiv", country: "Bulgaria", lat: 42.51, lon: 24.71 },
  { name: "Kalofer", region: "Plovdiv", country: "Bulgaria", lat: 42.61, lon: 24.97 },
  { name: "Karlovo", region: "Plovdiv", country: "Bulgaria", lat: 42.64, lon: 24.81 },
  { name: "Klisura", region: "Plovdiv", country: "Bulgaria", lat: 42.69, lon: 24.45 },
  { name: "Krichim", region: "Plovdiv", country: "Bulgaria", lat: 42.04, lon: 24.46 },
  { name: "Kuklen", region: "Plovdiv", country: "Bulgaria", lat: 42.03, lon: 24.79 },
  { name: "Laki", region: "Plovdiv", country: "Bulgaria", lat: 41.83, lon: 24.83 },
  { name: "Parvomay", region: "Plovdiv", country: "Bulgaria", lat: 42.10, lon: 25.22 },
  { name: "Perushtitsa", region: "Plovdiv", country: "Bulgaria", lat: 42.06, lon: 24.54 },
  { name: "Plovdiv", region: "Plovdiv", country: "Bulgaria", lat: 42.14, lon: 24.74 },
  { name: "Rakovski", region: "Plovdiv", country: "Bulgaria", lat: 42.29, lon: 24.97 },
  { name: "Sadovo", region: "Plovdiv", country: "Bulgaria", lat: 42.13, lon: 24.94 },
  { name: "Saedinenie", region: "Plovdiv", country: "Bulgaria", lat: 42.27, lon: 24.55 },
  { name: "Sopot", region: "Plovdiv", country: "Bulgaria", lat: 42.65, lon: 24.76 },
  { name: "Stamboliyski", region: "Plovdiv", country: "Bulgaria", lat: 42.13, lon: 24.54 },
  // Varna (11)
  { name: "Aksakovo", region: "Varna", country: "Bulgaria", lat: 43.26, lon: 27.82 },
  { name: "Beloslav", region: "Varna", country: "Bulgaria", lat: 43.19, lon: 27.71 },
  { name: "Byala", region: "Varna", country: "Bulgaria", lat: 42.88, lon: 27.89 },
  { name: "Dalgopol", region: "Varna", country: "Bulgaria", lat: 43.05, lon: 27.35 },
  { name: "Devnya", region: "Varna", country: "Bulgaria", lat: 43.22, lon: 27.56 },
  { name: "Dolni Chiflik", region: "Varna", country: "Bulgaria", lat: 42.99, lon: 27.72 },
  { name: "Ignatievo", region: "Varna", country: "Bulgaria", lat: 43.25, lon: 27.78 },
  { name: "Provadia", region: "Varna", country: "Bulgaria", lat: 43.17, lon: 27.44 },
  { name: "Suvorovo", region: "Varna", country: "Bulgaria", lat: 43.33, lon: 27.59 },
  { name: "Valchi Dol", region: "Varna", country: "Bulgaria", lat: 43.41, lon: 27.55 },
  { name: "Varna", region: "Varna", country: "Bulgaria", lat: 43.21, lon: 27.91 },
  // Burgas (20)
  { name: "Aheloy", region: "Burgas", country: "Bulgaria", lat: 42.65, lon: 27.65 },
  { name: "Ahtopol", region: "Burgas", country: "Bulgaria", lat: 42.10, lon: 27.94 },
  { name: "Aytos", region: "Burgas", country: "Bulgaria", lat: 42.70, lon: 27.25 },
  { name: "Balgarovo", region: "Burgas", country: "Bulgaria", lat: 42.62, lon: 27.31 },
  { name: "Burgas", region: "Burgas", country: "Bulgaria", lat: 42.50, lon: 27.47 },
  { name: "Chernomorets", region: "Burgas", country: "Bulgaria", lat: 42.44, lon: 27.64 },
  { name: "Kableshkovo", region: "Burgas", country: "Bulgaria", lat: 42.66, lon: 27.57 },
  { name: "Kameno", region: "Burgas", country: "Bulgaria", lat: 42.57, lon: 27.29 },
  { name: "Karnobat", region: "Burgas", country: "Bulgaria", lat: 42.65, lon: 26.98 },
  { name: "Kiten", region: "Burgas", country: "Bulgaria", lat: 42.23, lon: 27.77 },
  { name: "Malko Tarnovo", region: "Burgas", country: "Bulgaria", lat: 41.98, lon: 27.52 },
  { name: "Nesebar", region: "Burgas", country: "Bulgaria", lat: 42.66, lon: 27.72 },
  { name: "Obzor", region: "Burgas", country: "Bulgaria", lat: 42.82, lon: 27.88 },
  { name: "Pomorie", region: "Burgas", country: "Bulgaria", lat: 42.56, lon: 27.64 },
  { name: "Primorsko", region: "Burgas", country: "Bulgaria", lat: 42.27, lon: 27.76 },
  { name: "Sozopol", region: "Burgas", country: "Bulgaria", lat: 42.42, lon: 27.69 },
  { name: "Sredets", region: "Burgas", country: "Bulgaria", lat: 42.34, lon: 27.18 },
  { name: "Sungurlare", region: "Burgas", country: "Bulgaria", lat: 42.76, lon: 26.77 },
  { name: "Sveti Vlas", region: "Burgas", country: "Bulgaria", lat: 42.71, lon: 27.76 },
  { name: "Tsarevo", region: "Burgas", country: "Bulgaria", lat: 42.17, lon: 27.85 },
  // Stara Zagora (11)
  { name: "Chirpan", region: "Stara Zagora", country: "Bulgaria", lat: 42.20, lon: 25.33 },
  { name: "Galabovo", region: "Stara Zagora", country: "Bulgaria", lat: 42.14, lon: 25.88 },
  { name: "Gurkovo", region: "Stara Zagora", country: "Bulgaria", lat: 42.66, lon: 25.80 },
  { name: "Kazanlak", region: "Stara Zagora", country: "Bulgaria", lat: 42.62, lon: 25.39 },
  { name: "Kran", region: "Stara Zagora", country: "Bulgaria", lat: 42.67, lon: 25.38 },
  { name: "Maglizh", region: "Stara Zagora", country: "Bulgaria", lat: 42.61, lon: 25.55 },
  { name: "Nikolaevo", region: "Stara Zagora", country: "Bulgaria", lat: 42.63, lon: 25.79 },
  { name: "Pavel Banya", region: "Stara Zagora", country: "Bulgaria", lat: 42.59, lon: 25.21 },
  { name: "Radnevo", region: "Stara Zagora", country: "Bulgaria", lat: 42.29, lon: 25.94 },
  { name: "Shipka", region: "Stara Zagora", country: "Bulgaria", lat: 42.71, lon: 25.33 },
  { name: "Stara Zagora", region: "Stara Zagora", country: "Bulgaria", lat: 42.42, lon: 25.63 },
  // Ruse (9)
  { name: "Borovo", region: "Ruse", country: "Bulgaria", lat: 43.49, lon: 25.81 },
  { name: "Byala", region: "Ruse", country: "Bulgaria", lat: 43.46, lon: 25.74 },
  { name: "Dve Mogili", region: "Ruse", country: "Bulgaria", lat: 43.59, lon: 25.87 },
  { name: "Glodzhevo", region: "Ruse", country: "Bulgaria", lat: 43.73, lon: 26.39 },
  { name: "Marten", region: "Ruse", country: "Bulgaria", lat: 43.92, lon: 26.08 },
  { name: "Ruse", region: "Ruse", country: "Bulgaria", lat: 43.84, lon: 25.95 },
  { name: "Senovo", region: "Ruse", country: "Bulgaria", lat: 43.65, lon: 26.36 },
  { name: "Slivo Pole", region: "Ruse", country: "Bulgaria", lat: 43.94, lon: 26.20 },
  { name: "Vetovo", region: "Ruse", country: "Bulgaria", lat: 43.70, lon: 26.26 },
  // Pleven (14)
  { name: "Belene", region: "Pleven", country: "Bulgaria", lat: 43.64, lon: 25.13 },
  { name: "Cherven Bryag", region: "Pleven", country: "Bulgaria", lat: 43.28, lon: 24.08 },
  { name: "Dolna Mitropolia", region: "Pleven", country: "Bulgaria", lat: 43.47, lon: 24.52 },
  { name: "Dolni Dabnik", region: "Pleven", country: "Bulgaria", lat: 43.41, lon: 24.44 },
  { name: "Gulyantsi", region: "Pleven", country: "Bulgaria", lat: 43.64, lon: 24.69 },
  { name: "Iskar", region: "Pleven", country: "Bulgaria", lat: 43.46, lon: 24.26 },
  { name: "Knezha", region: "Pleven", country: "Bulgaria", lat: 43.49, lon: 24.08 },
  { name: "Koynare", region: "Pleven", country: "Bulgaria", lat: 43.36, lon: 24.14 },
  { name: "Levski", region: "Pleven", country: "Bulgaria", lat: 43.36, lon: 25.14 },
  { name: "Nikopol", region: "Pleven", country: "Bulgaria", lat: 43.70, lon: 24.89 },
  { name: "Pleven", region: "Pleven", country: "Bulgaria", lat: 43.41, lon: 24.62 },
  { name: "Pordim", region: "Pleven", country: "Bulgaria", lat: 43.38, lon: 24.85 },
  { name: "Slavyanovo", region: "Pleven", country: "Bulgaria", lat: 43.47, lon: 24.87 },
  { name: "Trastenik", region: "Pleven", country: "Bulgaria", lat: 43.52, lon: 24.47 },
  // Sliven (6)
  { name: "Kermen", region: "Sliven", country: "Bulgaria", lat: 42.51, lon: 26.26 },
  { name: "Kotel", region: "Sliven", country: "Bulgaria", lat: 42.89, lon: 26.45 },
  { name: "Nova Zagora", region: "Sliven", country: "Bulgaria", lat: 42.49, lon: 26.02 },
  { name: "Shivachevo", region: "Sliven", country: "Bulgaria", lat: 42.69, lon: 26.03 },
  { name: "Sliven", region: "Sliven", country: "Bulgaria", lat: 42.68, lon: 26.33 },
  { name: "Tvarditsa", region: "Sliven", country: "Bulgaria", lat: 42.70, lon: 25.90 },
  // Dobrich (6)
  { name: "Balchik", region: "Dobrich", country: "Bulgaria", lat: 43.41, lon: 28.17 },
  { name: "Dobrich", region: "Dobrich", country: "Bulgaria", lat: 43.57, lon: 27.83 },
  { name: "General Toshevo", region: "Dobrich", country: "Bulgaria", lat: 43.70, lon: 28.04 },
  { name: "Kavarna", region: "Dobrich", country: "Bulgaria", lat: 43.44, lon: 28.34 },
  { name: "Shabla", region: "Dobrich", country: "Bulgaria", lat: 43.54, lon: 28.53 },
  { name: "Tervel", region: "Dobrich", country: "Bulgaria", lat: 43.75, lon: 27.41 },
  // Shumen (8)
  { name: "Kaolinovo", region: "Shumen", country: "Bulgaria", lat: 43.62, lon: 27.09 },
  { name: "Kaspichan", region: "Shumen", country: "Bulgaria", lat: 43.32, lon: 27.16 },
  { name: "Novi Pazar", region: "Shumen", country: "Bulgaria", lat: 43.35, lon: 27.20 },
  { name: "Pliska", region: "Shumen", country: "Bulgaria", lat: 43.36, lon: 27.13 },
  { name: "Shumen", region: "Shumen", country: "Bulgaria", lat: 43.27, lon: 26.93 },
  { name: "Smyadovo", region: "Shumen", country: "Bulgaria", lat: 43.06, lon: 27.02 },
  { name: "Varbitsa", region: "Shumen", country: "Bulgaria", lat: 42.99, lon: 26.67 },
  { name: "Veliki Preslav", region: "Shumen", country: "Bulgaria", lat: 43.16, lon: 26.81 },
  // Pernik (6)
  { name: "Batanovtsi", region: "Pernik", country: "Bulgaria", lat: 42.60, lon: 22.96 },
  { name: "Breznik", region: "Pernik", country: "Bulgaria", lat: 42.74, lon: 22.91 },
  { name: "Pernik", region: "Pernik", country: "Bulgaria", lat: 42.60, lon: 23.03 },
  { name: "Radomir", region: "Pernik", country: "Bulgaria", lat: 42.55, lon: 22.96 },
  { name: "Tran", region: "Pernik", country: "Bulgaria", lat: 42.83, lon: 22.65 },
  { name: "Zemen", region: "Pernik", country: "Bulgaria", lat: 42.48, lon: 22.75 },
  // Haskovo (10)
  { name: "Dimitrovgrad", region: "Haskovo", country: "Bulgaria", lat: 42.06, lon: 25.59 },
  { name: "Harmanli", region: "Haskovo", country: "Bulgaria", lat: 41.93, lon: 25.91 },
  { name: "Haskovo", region: "Haskovo", country: "Bulgaria", lat: 41.93, lon: 25.56 },
  { name: "Ivaylovgrad", region: "Haskovo", country: "Bulgaria", lat: 41.53, lon: 26.12 },
  { name: "Lyubimets", region: "Haskovo", country: "Bulgaria", lat: 41.84, lon: 26.08 },
  { name: "Madzharovo", region: "Haskovo", country: "Bulgaria", lat: 41.63, lon: 25.86 },
  { name: "Merichleri", region: "Haskovo", country: "Bulgaria", lat: 42.13, lon: 25.50 },
  { name: "Simeonovgrad", region: "Haskovo", country: "Bulgaria", lat: 42.03, lon: 25.83 },
  { name: "Svilengrad", region: "Haskovo", country: "Bulgaria", lat: 41.77, lon: 26.20 },
  { name: "Topolovgrad", region: "Haskovo", country: "Bulgaria", lat: 42.08, lon: 26.34 },
  // Blagoevgrad (13)
  { name: "Bansko", region: "Blagoevgrad", country: "Bulgaria", lat: 41.84, lon: 23.49 },
  { name: "Belitsa", region: "Blagoevgrad", country: "Bulgaria", lat: 41.95, lon: 23.56 },
  { name: "Blagoevgrad", region: "Blagoevgrad", country: "Bulgaria", lat: 42.02, lon: 23.10 },
  { name: "Dobrinishte", region: "Blagoevgrad", country: "Bulgaria", lat: 41.82, lon: 23.56 },
  { name: "Gotse Delchev", region: "Blagoevgrad", country: "Bulgaria", lat: 41.57, lon: 23.73 },
  { name: "Hadzhidimovo", region: "Blagoevgrad", country: "Bulgaria", lat: 41.52, lon: 23.85 },
  { name: "Kresna", region: "Blagoevgrad", country: "Bulgaria", lat: 41.72, lon: 23.16 },
  { name: "Melnik", region: "Blagoevgrad", country: "Bulgaria", lat: 41.52, lon: 23.39 },
  { name: "Petrich", region: "Blagoevgrad", country: "Bulgaria", lat: 41.40, lon: 23.21 },
  { name: "Razlog", region: "Blagoevgrad", country: "Bulgaria", lat: 41.89, lon: 23.47 },
  { name: "Sandanski", region: "Blagoevgrad", country: "Bulgaria", lat: 41.57, lon: 23.28 },
  { name: "Simitli", region: "Blagoevgrad", country: "Bulgaria", lat: 41.89, lon: 23.11 },
  { name: "Yakoruda", region: "Blagoevgrad", country: "Bulgaria", lat: 42.02, lon: 23.67 },
  // Yambol (4)
  { name: "Bolyarovo", region: "Yambol", country: "Bulgaria", lat: 42.15, lon: 26.81 },
  { name: "Elhovo", region: "Yambol", country: "Bulgaria", lat: 42.17, lon: 26.57 },
  { name: "Straldzha", region: "Yambol", country: "Bulgaria", lat: 42.60, lon: 26.69 },
  { name: "Yambol", region: "Yambol", country: "Bulgaria", lat: 42.48, lon: 26.50 },
  // Veliko Tarnovo (14)
  { name: "Byala Cherkva", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.21, lon: 25.31 },
  { name: "Debelets", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.04, lon: 25.62 },
  { name: "Dolna Oryahovitsa", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.16, lon: 25.74 },
  { name: "Elena", region: "Veliko Tarnovo", country: "Bulgaria", lat: 42.93, lon: 25.88 },
  { name: "Gorna Oryahovitsa", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.12, lon: 25.69 },
  { name: "Kilifarevo", region: "Veliko Tarnovo", country: "Bulgaria", lat: 42.99, lon: 25.62 },
  { name: "Lyaskovets", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.11, lon: 25.71 },
  { name: "Pavlikeni", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.24, lon: 25.31 },
  { name: "Polski Trambesh", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.37, lon: 25.64 },
  { name: "Strazhitsa", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.23, lon: 25.96 },
  { name: "Suhindol", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.19, lon: 25.17 },
  { name: "Svishtov", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.62, lon: 25.35 },
  { name: "Veliko Tarnovo", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.08, lon: 25.63 },
  { name: "Zlataritsa", region: "Veliko Tarnovo", country: "Bulgaria", lat: 43.05, lon: 25.89 },
  // Pazardzhik (13)
  { name: "Batak", region: "Pazardzhik", country: "Bulgaria", lat: 41.94, lon: 24.22 },
  { name: "Belovo", region: "Pazardzhik", country: "Bulgaria", lat: 42.21, lon: 24.02 },
  { name: "Bratsigovo", region: "Pazardzhik", country: "Bulgaria", lat: 42.02, lon: 24.37 },
  { name: "Kostandovo", region: "Pazardzhik", country: "Bulgaria", lat: 42.02, lon: 24.11 },
  { name: "Panagyurishte", region: "Pazardzhik", country: "Bulgaria", lat: 42.50, lon: 24.18 },
  { name: "Pazardzhik", region: "Pazardzhik", country: "Bulgaria", lat: 42.19, lon: 24.33 },
  { name: "Peshtera", region: "Pazardzhik", country: "Bulgaria", lat: 42.03, lon: 24.30 },
  { name: "Rakitovo", region: "Pazardzhik", country: "Bulgaria", lat: 41.99, lon: 24.09 },
  { name: "Sarnitsa", region: "Pazardzhik", country: "Bulgaria", lat: 41.74, lon: 24.02 },
  { name: "Septemvri", region: "Pazardzhik", country: "Bulgaria", lat: 42.22, lon: 24.13 },
  { name: "Strelcha", region: "Pazardzhik", country: "Bulgaria", lat: 42.50, lon: 24.32 },
  { name: "Velingrad", region: "Pazardzhik", country: "Bulgaria", lat: 42.03, lon: 23.99 },
  { name: "Vetren", region: "Pazardzhik", country: "Bulgaria", lat: 42.28, lon: 24.05 },
  // Vratsa (8)
  { name: "Byala Slatina", region: "Vratsa", country: "Bulgaria", lat: 43.47, lon: 23.95 },
  { name: "Kozloduy", region: "Vratsa", country: "Bulgaria", lat: 43.78, lon: 23.73 },
  { name: "Krivodol", region: "Vratsa", country: "Bulgaria", lat: 43.37, lon: 23.48 },
  { name: "Mezdra", region: "Vratsa", country: "Bulgaria", lat: 43.14, lon: 23.71 },
  { name: "Mizia", region: "Vratsa", country: "Bulgaria", lat: 43.69, lon: 23.85 },
  { name: "Oryahovo", region: "Vratsa", country: "Bulgaria", lat: 43.74, lon: 23.96 },
  { name: "Roman", region: "Vratsa", country: "Bulgaria", lat: 43.15, lon: 23.93 },
  { name: "Vratsa", region: "Vratsa", country: "Bulgaria", lat: 43.20, lon: 23.55 },
  // Gabrovo (5)
  { name: "Dryanovo", region: "Gabrovo", country: "Bulgaria", lat: 42.97, lon: 25.47 },
  { name: "Gabrovo", region: "Gabrovo", country: "Bulgaria", lat: 42.87, lon: 25.32 },
  { name: "Plachkovtsi", region: "Gabrovo", country: "Bulgaria", lat: 42.83, lon: 25.48 },
  { name: "Sevlievo", region: "Gabrovo", country: "Bulgaria", lat: 43.02, lon: 25.10 },
  { name: "Tryavna", region: "Gabrovo", country: "Bulgaria", lat: 42.87, lon: 25.49 },
  // Kardzhali (5)
  { name: "Ardino", region: "Kardzhali", country: "Bulgaria", lat: 41.58, lon: 25.13 },
  { name: "Dzhebel", region: "Kardzhali", country: "Bulgaria", lat: 41.50, lon: 25.30 },
  { name: "Kardzhali", region: "Kardzhali", country: "Bulgaria", lat: 41.64, lon: 25.37 },
  { name: "Krumovgrad", region: "Kardzhali", country: "Bulgaria", lat: 41.47, lon: 25.65 },
  { name: "Momchilgrad", region: "Kardzhali", country: "Bulgaria", lat: 41.53, lon: 25.41 },
  // Montana (8)
  { name: "Berkovitsa", region: "Montana", country: "Bulgaria", lat: 43.24, lon: 23.13 },
  { name: "Boychinovtsi", region: "Montana", country: "Bulgaria", lat: 43.47, lon: 23.34 },
  { name: "Brusartsi", region: "Montana", country: "Bulgaria", lat: 43.66, lon: 23.07 },
  { name: "Chiprovtsi", region: "Montana", country: "Bulgaria", lat: 43.38, lon: 22.88 },
  { name: "Lom", region: "Montana", country: "Bulgaria", lat: 43.83, lon: 23.24 },
  { name: "Montana", region: "Montana", country: "Bulgaria", lat: 43.41, lon: 23.22 },
  { name: "Valchedram", region: "Montana", country: "Bulgaria", lat: 43.70, lon: 23.44 },
  { name: "Varshets", region: "Montana", country: "Bulgaria", lat: 43.20, lon: 23.29 },
  // Kyustendil (7)
  { name: "Boboshevo", region: "Kyustendil", country: "Bulgaria", lat: 42.15, lon: 23.00 },
  { name: "Bobov Dol", region: "Kyustendil", country: "Bulgaria", lat: 42.36, lon: 23.00 },
  { name: "Dupnitsa", region: "Kyustendil", country: "Bulgaria", lat: 42.26, lon: 23.12 },
  { name: "Kocherinovo", region: "Kyustendil", country: "Bulgaria", lat: 42.09, lon: 23.06 },
  { name: "Kyustendil", region: "Kyustendil", country: "Bulgaria", lat: 42.28, lon: 22.69 },
  { name: "Rila", region: "Kyustendil", country: "Bulgaria", lat: 42.13, lon: 23.13 },
  { name: "Sapareva Banya", region: "Kyustendil", country: "Bulgaria", lat: 42.29, lon: 23.26 },
  // Targovishte (5)
  { name: "Antonovo", region: "Targovishte", country: "Bulgaria", lat: 43.15, lon: 26.16 },
  { name: "Omurtag", region: "Targovishte", country: "Bulgaria", lat: 43.11, lon: 26.42 },
  { name: "Opaka", region: "Targovishte", country: "Bulgaria", lat: 43.45, lon: 26.17 },
  { name: "Popovo", region: "Targovishte", country: "Bulgaria", lat: 43.35, lon: 26.23 },
  { name: "Targovishte", region: "Targovishte", country: "Bulgaria", lat: 43.24, lon: 26.57 },
  // Razgrad (6)
  { name: "Isperih", region: "Razgrad", country: "Bulgaria", lat: 43.72, lon: 26.83 },
  { name: "Kubrat", region: "Razgrad", country: "Bulgaria", lat: 43.80, lon: 26.50 },
  { name: "Loznitsa", region: "Razgrad", country: "Bulgaria", lat: 43.37, lon: 26.60 },
  { name: "Razgrad", region: "Razgrad", country: "Bulgaria", lat: 43.53, lon: 26.53 },
  { name: "Tsar Kaloyan", region: "Razgrad", country: "Bulgaria", lat: 43.61, lon: 26.24 },
  { name: "Zavet", region: "Razgrad", country: "Bulgaria", lat: 43.76, lon: 26.68 },
  // Lovech (8)
  { name: "Apriltsi", region: "Lovech", country: "Bulgaria", lat: 42.84, lon: 24.92 },
  { name: "Letnitsa", region: "Lovech", country: "Bulgaria", lat: 43.31, lon: 25.05 },
  { name: "Lovech", region: "Lovech", country: "Bulgaria", lat: 43.13, lon: 24.71 },
  { name: "Lukovit", region: "Lovech", country: "Bulgaria", lat: 43.21, lon: 24.16 },
  { name: "Teteven", region: "Lovech", country: "Bulgaria", lat: 42.92, lon: 24.26 },
  { name: "Troyan", region: "Lovech", country: "Bulgaria", lat: 42.89, lon: 24.71 },
  { name: "Ugarchin", region: "Lovech", country: "Bulgaria", lat: 43.10, lon: 24.42 },
  { name: "Yablanitsa", region: "Lovech", country: "Bulgaria", lat: 43.03, lon: 24.10 },
  // Silistra (5)
  { name: "Alfatar", region: "Silistra", country: "Bulgaria", lat: 43.95, lon: 27.29 },
  { name: "Dulovo", region: "Silistra", country: "Bulgaria", lat: 43.82, lon: 27.14 },
  { name: "Glavinitsa", region: "Silistra", country: "Bulgaria", lat: 43.91, lon: 26.83 },
  { name: "Silistra", region: "Silistra", country: "Bulgaria", lat: 44.11, lon: 27.26 },
  { name: "Tutrakan", region: "Silistra", country: "Bulgaria", lat: 44.04, lon: 26.61 },
  // Smolyan (8)
  { name: "Chepelare", region: "Smolyan", country: "Bulgaria", lat: 41.72, lon: 24.69 },
  { name: "Devin", region: "Smolyan", country: "Bulgaria", lat: 41.74, lon: 24.40 },
  { name: "Dospat", region: "Smolyan", country: "Bulgaria", lat: 41.65, lon: 24.16 },
  { name: "Madan", region: "Smolyan", country: "Bulgaria", lat: 41.50, lon: 24.94 },
  { name: "Nedelino", region: "Smolyan", country: "Bulgaria", lat: 41.46, lon: 25.08 },
  { name: "Rudozem", region: "Smolyan", country: "Bulgaria", lat: 41.49, lon: 24.85 },
  { name: "Smolyan", region: "Smolyan", country: "Bulgaria", lat: 41.58, lon: 24.70 },
  { name: "Zlatograd", region: "Smolyan", country: "Bulgaria", lat: 41.38, lon: 25.09 },
  // Vidin (7)
  { name: "Belogradchik", region: "Vidin", country: "Bulgaria", lat: 43.63, lon: 22.69 },
  { name: "Bregovo", region: "Vidin", country: "Bulgaria", lat: 44.15, lon: 22.64 },
  { name: "Dimovo", region: "Vidin", country: "Bulgaria", lat: 43.74, lon: 22.73 },
  { name: "Dunavtsi", region: "Vidin", country: "Bulgaria", lat: 43.91, lon: 22.81 },
  { name: "Gramada", region: "Vidin", country: "Bulgaria", lat: 43.83, lon: 22.66 },
  { name: "Kula", region: "Vidin", country: "Bulgaria", lat: 43.89, lon: 22.52 },
  { name: "Vidin", region: "Vidin", country: "Bulgaria", lat: 43.99, lon: 22.87 },
];
